# For more information: https://laravel.com/docs/sail
version: '3.8'
services:

  php:
    image: registry.cevi.tools/cevi/qualitool_php_fpm:latest
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    networks:
      - internal-net
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ENV_FILE_PATH=/run/secrets/.env
    volumes:
      - .env:/run/secrets/.env

  nginx:
    image: registry.cevi.tools/cevi/qualitool_nginx:latest
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal-net
    depends_on:
      - php

  mysql:
    image: registry.cevi.tools/cevi/qualitool_mysql_server:latest
    build:
      context: .
      dockerfile: docker/mysql.Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - mysql-data-production:/var/lib/mysql
      - .env:/run/secrets/.env
    environment:
      - ENV_FILE_PATH=/run/secrets/.env
    networks:
      - internal-net
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

networks:
  internal-net:
    driver: bridge

volumes:
  mysql-data-production:
    driver: local
